### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by duckupus** [Mini-Ware/Qubit#30]
Add an Chat reviver function to give an topic or question for an chat to talk about after a certain amount of time with no messages

**Comment by Mini-Ware** [comment]
I don't think I would apply this to all servers, since some server may not want it. Maybe for certain servers that you want I can do it?

**Comment by duckupus** [comment]
maybe it can be toggled by whichever server wants it to be on so that they can choose if they want to receive it or not?
