### ISSUE TITLE
qubit does not respond to /wyr when used quickly

### ISSUE THREAD

**Issue by duckupus** [Mini-Ware/Qubit#36]
# How to replicate
- use /wyr multiple times, quickly
- after 10 or so times, qubit stops responding to /wyr and throws an error instead.

# Expected behaviour
- for it to respond to multiple /wyr requests

NOTE: This may be used as a DoS attempt, effects not fully tested at time of submission.

**Comment by Mini-Ware** [comment]
this issue seems to be with slash commands after looking at the logs, but I will look into it soon

Error [INTERACTION_NOT_REPLIED]: The reply to this interaction has not been sent or deferred.
    at CommandInteraction.editReply (/workspace/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:136:48)
    at /workspace/src/index.js:201:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INTERACTION_NOT_REPLIED'
}

Another issue found and fixed, thank you!
